services:
  - type: web
    name: itaccess-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: "dpg-d7egn1n7f7vs739bvh10-a"
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: "itaccess"
      - key: DB_USER
        value: "itaccess_user"
      - key: DB_PASSWORD
        value: "Vij9E2rXltNYcSMn6S2kKuqgOqWqRlXA"
      - key: JWT_SECRET
        generateValue: true
      - key: SERVER_PORT
        value: "8000"
